#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

# Merges sound with a sequence of vids
# $1: output file
# $2: sound file
# $@: videos
_audiovid2vid() {
  local \
    _out="${1}"
    _aud="${2}"
  shift 2
  local \
    _pics=("${@}") \
    _tmp
  _tmp="$(mktemp -d)"

  ffmpeg \
    -loop 1 \
    -i "${_vids[@]}" \
    -i "${_aud}" \
    -c:v libx264 \
    -c:a aac \
    -b:a 48k \
    -pix_fmt yuv420p \
    -shortest "${_out}"
}

_usage() {
  local \
    _exit_code="${1}"
  echo \
    "Usage: audiovid2vid <output_video> <input_audio> [input_video]"
  exit \
    "${_exit_code}"
}

_out="${1}"
_aud="${2}"
shift 2
_vids=(
  "${@}")

(( $# < 3 )) && \
  _usage \
    1

_audiovid2vid \
  "${_out}" \
  "${_aud}" \
  "${_vids[@]}"
