#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_global_variables() {
	input_sound=""
	input_pictures=()
  output_video=""
}

_audiopic2vid() {
  local \
    _output_video="${1}" \
    _input_sound="${2}" \
    _input_pictures=() \
    _mktemp_opts=() \
    _ffmpeg_opts=() \
    _pic
  shift \
    2
  _input_pictures+=(
    "$@"
  )
  ffmpeg_opts+=(
    -loop
      1
  )
  for _pic in "${_input_pictures[@]}"; do
    ffmpeg_opts+=(
      -i
        "${_pic}"
    )
  done
  ffmpeg_opts+=(
    -i
      "${_input_sound}"
    -c:v
      "libx264"
    -tune
      "stillimage"
    -c:a
      "aac"
    -b:a
      "48k"
    -pix_fmt
      "yuv420p"
    -shortest
  )
  ffmpeg \
    "${_ffmpeg_opts[@]}" \
    "${_output_video}"
}

_usage() {
  local \
    _exit="${1}" \
    _line \
    _text
  _text=(
    "Create slideshow with sound."
    ""
    "  usage:"
    "    audiopic2vid"
    "      <output-video>"
    "      <input-sound>"
    "      [input-picture]"
    ""
    "  options:"
    "    -h          This help."
    ""
  )
  printf \
    "%s\n" \
    "${_text[@]}"
  exit \
    "${_exit}"
}

_cmdline_parse() {
  local \
    _args=() \
    _msg=()
  _args+=(
    "$@"
  )
  if [[ " ${_args[*]} " == *" -h "* ||
        " ${_args[*]} " == *" --help "* ]]; then
    _usage \
      0
  fi
  if (( "${#_args[@]}" < 3 )); then
    _msg=(
      "Missing argument."
    )
    echo \
      "${_msg[*]}" \
      1>&2
    _usage \
      1
  fi
}

_global_variables
_cmdline_parse \
  "$@"
output_video="${1}"
input_sound="${2}"
shift \
  2
input_pictures=(
  "$@"
)
app_opts=(
  "${output_video}"
  "${input_sound}"
  "${input_pictures[@]}"
)

_audiopic2vid \
  "${app_opts[@]}"
