#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  in_files=()
  out_file=""
  encode_mode=""
  encode_date=""
  color=""
  quiet=""
}

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    "ffmpeg"
  _check_cmd \
    "bc"
}

_ffmpeg_options_load() {
  local \
    ffmpeg_options
  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
  [ -e "${ffmpeg_options}" ] && \
    source \
      "${ffmpeg_options}" || \
  true
}

# Scale audio file duration
# $1: output video file
# $2: scale
# $@: input video files (sorted)
_audioscale() {
  local \
    _out="${1}" \
    _scale="${2}" \
    _i=1 \
    _in=() \
    _opts=() \
    _vf="" \
    _vid \
    _vids=()
  shift \
    2 
  _in=(
    "$@"
  )
  _length="$( \
    medialength \
      "${_in[@]}")"
  if (( "" < 1 )); then
    if $(echo "${_scale} < 0.5" | bc -l);
  fi
  _scale="$( \
    echo \
      "${_length}" | \
      bc
    )"
  _vids="$( \
    mktemp \
      --suffix \
        ".txt")"
  for _vid \
    in "${_in[@]}"; do
    _vid="$( \
      realpath \
        "${_vid}")"
    echo \
      "file '${_vid}'" >> \
      "${_vids}"
   _vf="${_vf} [${_i}:v] [${_i}:a]"
   _i=$((_i + 1))
  done
  _vf="${_vf} concat=n=${_i}:v=1:a=1 [v] [a]"
  _msg_info \
    "vids: $( \
       cat \
         "${_vids}")"
  _opts=(
    "${_ffmpeg_opts[@]}"
    -safe
      0
    -i
      ${_vids}
    -filter_complex
      "${_vf}"
    -map
      "[v]"
    -map
      "[a]"
    -f
      mp4
    -vcodec
      libx265
  )

ffmpeg -i ~/storage/movies/ciaoneoneone.m4a  -filter_complex "[0:a]atempo=0.5[a]" -map "[a]" ~/storage/movies/cine.m4a
  if [[ "${_mode}" == 'filter' ]]; then
    ffmpeg \
      "${_opts[@]}" \
      "${_out}" || \
      true
  elif [[ "${_mode}" == 'protocol' ]]; then
      _msg_info \
        "running ffmpeg with concat protocol method"
      _protocol
  elif [[ "${_mode}" == 'concat' ]]; then
    # echo \
    #   "${_mm}"
    # [[ ! $? -eq 0 ]] && \
      _msg_info \
        "running ffmpeg with concat method"
      _concat
  fi
  return \
    0
}

# Set defaults and, if present, overrides
# from command line option parameters
_set_overrides() {
  _set_override \
    "scale" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "scale" \
    "factor" \
    "protocol"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "               Scale date:   $(_get "scale" "date")"
  _msg_info "             Scale factor:   $(_get "scale" "factor")"
  _msg_info "                 In files:   ${in_files[*]}"
  _msg_info "              Output file:   $(_get "out" "file")"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Scale audio duration

Usage:
  $(_get "app" "name")
    [options]
    <output_file>
    <scale_factor>
    [input_file]
  options:
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'cvh?' \
    arg; do
  case \
    "${arg}" in
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
(( ${#} < 2 )) && \
  _usage \
    1
_set \
  "out" \
  "file" \
  "${1}"
shift \
  1
in_files=(
  "$@"
)
_set_overrides
app_opts=(
  "$(_get \
       "out" \
       "file")"
  "$(_get \
       "scale" \
       "factor")"
  "${in_files[@]}"
)
_config_user_init \
  "media-tools"
_show_config
_ffmpeg_options_load
_audioscale \
  "${app_opts[@]}"
