#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" || \
source \
  "${_crash_bash}"

_global_variables() {
  make_date=""
  normalization_type=""
  input_sound=""
  input_pictures=()
  sound_encode=""
  output_video=""
  span_type=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    "bc"
}

_min_max_get() {
  local \
    _input_pictures=() \
    _height \
    _width
  _input_pictures+=(
    "$@"
  )
  _height_max=0
  _height_min=0
  _width_max=0
  _width_min=0
  for _pic in "${_input_pictures[@]}"; do
    _height="$(
      mediasize \
        -H \
        "${_pic}")"
    _width="$(
      mediasize \
        -W \
        "${_pic}")"
    _msg=(
      "Picture '${_pic}' has size"
      "${_width}x${_height}".
    )
    _msg_info \
      "${_msg[*]}"
    if (( "${_height_max}" < "${_height}" )); then
      _height_max="${_height}"
    fi
    if (( "${_height}" < "${_height_min}" )); then
      _height_min="${_height}"
    fi
    if (( "${_width_max}" < "${_width}" )); then
      _width_max="${_width}"
    fi
    if (( "${_width}" < "${_width_min}" )); then
      _width_min="${_width}"
    fi
  done
}

_normalize() {
  local \
    _input_pictures=() \
    _ffmpeg_opts=() \
    _scale_opts=() \
    _pic \
    _pic_scaled \
    _height \
    _height_max \
    _pad_height \
    _pad_opt \
    _pad_width \
    _width \
    _width_max \
    _scale_opt \
    _vf \
    _msg=()
  _input_pictures+=(
    "$@"
  )
  _min_max_get \
    "${_input_pictures[@]}"
  if [[ "${_normalization_type}" == "max" ]]; then
    _scale_opt="scale=${_width_max}:${_height_max}"
  elif [[ "${_normalization_type}" == "min" ]]; then
    _scale_opt="scale=${_width_min}:${_height_min}"
  else
    _msg=(
      "Invalid value '${_normalization_type}'"
      "for normalization type parameter, allowed"
      "types are 'min' and 'max'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  if [[ "${_normalization_type}" != "" ]]; then
    _msg=(
      "Pictures' size is not uniform,"
      "rescaling up to '${_normalization_type}'."
    )
    _msg_info \
      "${_msg[*]}"
  fi
  if [[ "${quiet}" == "n" ]]; then
    _ffmpeg_opts+=(
      -v
        1
    )
  fi
  for _pic in "${_input_pictures[@]}"; do
    _pic_scaled="${_pic}.scaled.jpg"
    _msg=(
      "Rescaling '${_pic}' onto '${_pic_scaled}'."
    )
    _msg_info \
      "${_msg[*]}"
    _vf="${_scale_opt}"
    _pad_width="0"
    _pad_height="0"
    _height="$(
      mediasize \
        -H \
        "${_pic}")"
    _width="$(
      mediasize \
        -W \
        "${_pic}")"
    if (( "${_height}" < "${_height_max}" )); then
      _pad_height="$((
        ( "${_height_max}" - "${_height}" ) /
          2 ))"
    fi
    if (( "${_height}" < "${_height_max}" )); then
      _pad_width="$((
        ( "${_width_max}" - "${_width}" ) /
          2 ))"
    fi
    if (( 0 < "${_pad_height}" || \
          0 < "${_pad_width}" )); then
      _pad_opt="pad=${_width_max}:${_height_max}:${_pad_width}:${_pad_height}:black"
      _vf="${_vf},${_pad_opt}"
    fi
    _scale_opts=(
      "${_ffmpeg_opts[@]}"
      -i
        "${_pic}"
      -vf
        "${_vf}"
    )
    _msg=(
      "Running ffmpeg with options '${_scale_opts[*]}'."
    )
    _msg_info \
      "${_msg[*]}"
    ffmpeg \
      "${_ffmpeg_opts[@]}" \
      -i \
        "${_pic}" \
      -vf \
        "${_vf}" \
      "${_pic_scaled}"
  done
}

_audiopic2vid() {
  local \
    _normalization_type="${1}" \
    _span_type="${2}" \
    _sound_encode="${3}" \
    _output_video="${4}" \
    _input_sound="${5}" \
    _input_pictures=() \
    _mktemp_opts=() \
    _ffmpeg_opts=() \
    _pic \
    _pic_length \
    _pics_amount \
    _length \
    _filter_complex
  shift \
    5
  _input_pictures+=(
    "$@"
  )
  _normalize \
    "${_input_pictures[@]}"
  _ffmpeg_opts+=(
    -i
      "${_input_sound}"
  )
  _length="$(
    medialength \
      "${_input_sound}")"
  _pics_amount="${#_input_pictures[@]}"
  if [[ "${_span_type}" == "uniform" ]]; then
    _bc_args=(
      "scale=2;"
      "${_length}" "/"
        "${#_input_pictures[@]}"
    )
    _pic_length="$(
      echo \
        "${_bc_args[*]}" |
        bc)"
  fi
  for _pic in "${_input_pictures[@]}"; do
    _ffmpeg_opts+=(
      -loop
        "1"
      -t
        "${_pic_length}"
      -i
        "${_pic}.scaled.jpg"
    )
  done
  _ffmpeg_opts+=(
    -c:v
      "libx264"
  )
  if (( "${_pics_amount}" < 2 )); then
    _ffmpeg_opts+=(
      -tune
        "stillimage"
      -pix_fmt
        "yuv420p"
      -shortest
    )
  else
    for _index \
      in $(seq \
           1 \
	   "$(( ${_pics_amount}  ))"); do
      _filter_complex+="[${_index}:v:0][0:a:0]"
    done
    _filter_complex+="concat=n=${_pics_amount}:a=1:v=1[outv][outa]"
    _ffmpeg_opts+=(
      -filter_complex
        "${_filter_complex}"
      -map
        "[outv]"
      -map
        "[outa]"
    )
  fi
  if [[ "${_sound_encode}" == "y" ]]; then
    _ffmpeg_opts+=(
      -c:a
        "aac"
      -b:a
        "48k"
    )
  else
    _ffmpeg_opts+=(
      -c:a
        "copy"
    )
  fi
  _msg=(
    "Running ffmpeg with options '${_ffmpeg_opts[@]}'."
  )
  _msg_info \
    "${_msg[*]}"
  ffmpeg \
    "${_ffmpeg_opts[@]}" \
    "${_output_video}"
  for _pic in "${_input_pictures[@]}"; do
    rm \
      "${_pic}.scaled.jpg"
  done
}

_usage() {
  local \
    _exit="${1}" \
    _line \
    _text
  _text=(
    "Create slideshow with sound."
    ""
    "  usage:"
    "    ${app_name}"
    "      <output-video>"
    "      <input-sound>"
    "      [input-picture]"
    ""
    "  options:"
    "    -n          Normalization type. Can be 'max' and"
    "                'min'."
    "                Default: ${normalization_type}."
    "    -t          Span type. Can be 'uniform'."
    "                Default: ${span_type}."
    "    -h          This help."
    ""
  )
  printf \
    "%s\n" \
    "${_text[@]}"
  exit \
    "${_exit}"
}

_cmdline_parse() {
  local \
    _args=() \
    _msg=()
  _args+=(
    "$@"
  )
  if [[ " ${_args[*]} " == *" -h "* ||
        " ${_args[*]} " == *" --help "* ]]; then
    _usage \
      0
  fi
  if (( "${#_args[@]}" < 3 )); then
    _msg=(
      "Missing argument."
    )
    echo \
      "${_msg[*]}" \
      1>&2
    _usage \
      1
  fi
  while \
    getopts \
      'n:t:ecvh?' \
      arg; do
    case \
      "${arg}" in
      n)
        override_normalize_type="${OPTARG}" ;;
      t)
        override_span_type="${OPTARG}" ;;
      e)
        override_sound_encode="n" ;;
      c)
        override_color="y" ;;
      v)
        override_quiet="n" ;;
      h|?)
        _set_overrides
        _usage \
          0 ;;
      *)
        _msg=(
          "Invalid argument '${arg}'"
        )
        _msg_error \
          "${_msg[*]}" \
          0
        _usage \
          1 ;;
    esac
  done
}

_input_sound_check() {
  local \
    _msg=()
  if [[ ! -e "${input_sound}" ]]; then
    _msg=(
      "Input sound file"
      "'${input_sound}' does not exist."
    )
    echo \
      "${_msg[*]}" \
      1>&2
    exit \
      1
  else
    input_sound="$(
      realpath \
        "${input_sound}")"
  fi
}

_sound_encode_auto_detect() {
  local \
    _pics_amount
  _pics_amount="${#input_pictures[@]}"
  if (( 1 < "${_pics_amount}" )); then
    _sound_encode="y"
  else
    _sound_encode="n"
  fi
  _set_override \
    "sound" \
    "encode" \
    "${_sound_encode}"
}

_normalization_type_auto_detect() {
  local \
    _pic \
    _pic_scale \
    _size \
    _size_compare
  _normalization_type=""
  _pic_scale="n"
  _size_compare="$(
    mediasize \
      -W \
      "${input_pictures[0]}")"
  for _pic \
    in "${input_pictures[@]}"; do
    _size="$(
      mediasize \
        "${_pic}")"
    if [[ "${_size}" != "${_size_compare}" ]]; then
      _pic_scale="y"
    fi
    break
  done
  if [[ "${_pic_scale}" == "y" ]]; then
    _normalization_type="max"
  fi
  _set_override \
    "normalization" \
    "type" \
    "${_normalization_type}"
}

# Set defaults and, if present, overrides
# from command line option parameters
_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "make" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "span" \
    "type" \
    "uniform"
  _sound_encode_auto_detect
  _normalization_type_auto_detect
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                Make date:   ${make_date}"
  _msg_info "                Span type:   ${span_type}"
  _msg_info "             Sound encode:   ${sound_encode}"
  _msg_info "              Output file:   ${output_video}"
  _msg_info "         Input sound file:   ${input_sound}"
  _msg_info "           Input pictures:"
  _show_config_input_pictures
}

_show_config_input_pictures() {
  local \
    _pic
  for _pic in "${input_pictures[@]}"; do
    _msg_info "                             ${_pic}"
  done
}

_globals
_global_variables

_cmdline_parse \
  "$@"
shift \
  $((
    OPTIND - 1 ))
output_video="${1}"
input_sound="${2}"
_input_sound_check
shift \
  2
input_pictures=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${normalization_type}"
  "${span_type}"
  "${sound_encode}"
  "${output_video}"
  "${input_sound}"
  "${input_pictures[@]}"
)
_audiopic2vid \
  "${app_opts[@]}"
