#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" || \
source \
  "${_crash_bash}"

_global_variables() {
  make_date=""
  input_sound=""
  input_pictures=()
  sound_encode=""
  output_video=""
  span_type=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    "bc"
}

_audiopic2vid() {
  local \
    _span_type="${1}" \
    _output_video="${2}" \
    _input_sound="${3}" \
    _input_pictures=() \
    _mktemp_opts=() \
    _ffmpeg_opts=() \
    _pic \
    _pic_length \
    _pics_amount \
    _length \
    _filter_complex
  shift \
    3
  _input_pictures+=(
    "$@"
  )
  _length="$(
    medialength \
      "${_input_sound}")"
  _pics_amount="${#_input_pictures[@]}"
  if [[ "${_span_type}" == "uniform" ]]; then
    _bc_args=(
      "scale=2;"
      "${_length}" "/"
        "${#_input_pictures[@]}"
    )
    _pic_length="$(
      echo \
        "${_bc_args[*]}" |
        bc)"
  fi
  for _pic in "${_input_pictures[@]}"; do
    ffmpeg_opts+=(
      -loop
        "1"
      -t
        "${_pic_length}"
      -i
        "${_pic}"
    )
  done
  ffmpeg_opts+=(
    -i
      "${_input_sound}"
    -c:v
      "libx264"
  )
  if (( "${_pic_amounts}" < 2 )); then
    ffmpeg_opts+=(
      -tune
        "stillimage"
    )
  else
    for _index \
      in seq \
           0 \
           "$(( ${_pic_amounts} - 1 ))"; do
      _filter_complex+="[${_index}:0]"
    done
    _filter_complex+="concat=n=${_pic_amounts}:v=1:a=1[v][a]; [v]format=yuv420p[v]"
    ffmpeg_opts+=(
      -filter_complex
        "${_filter_complex}"
      -map
        "[v]"
      -map
        "[a]"
    )
  fi
  if [[ "${_sound_encode}" == "y" ]]; then
    ffmpeg_opts+=(
      -c:a
        "aac"
      -b:a
        "48k"
    )
  else
    ffmpeg_opts+=(
      -c:a
        "copy"
    )
  fi
  ffmpeg_opts+=(
    -pix_fmt
      "yuv420p"
    -shortest
  )
  ffmpeg \
    "${_ffmpeg_opts[@]}" \
    "${_output_video}"
}

_usage() {
  local \
    _exit="${1}" \
    _line \
    _text
  _text=(
    "Create slideshow with sound."
    ""
    "  usage:"
    "    audiopic2vid"
    "      <output-video>"
    "      <input-sound>"
    "      [input-picture]"
    ""
    "  options:"
    "    -t          Span type. Can be 'uniform'."
    "                Default: ${span_type}."
    "    -h          This help."
    ""
  )
  printf \
    "%s\n" \
    "${_text[@]}"
  exit \
    "${_exit}"
}

_cmdline_parse() {
  local \
    _args=() \
    _msg=()
  _args+=(
    "$@"
  )
  if [[ " ${_args[*]} " == *" -h "* ||
        " ${_args[*]} " == *" --help "* ]]; then
    _usage \
      0
  fi
  if (( "${#_args[@]}" < 3 )); then
    _msg=(
      "Missing argument."
    )
    echo \
      "${_msg[*]}" \
      1>&2
    _usage \
      1
  fi
  while \
    getopts \
      't:ecvh?' \
      arg; do
    case \
      "${arg}" in
      t)
        override_span_type="${OPTARG}" ;;
      e)
        override_sound_encode="y" ;;
      c)
        override_color="y" ;;
      v)
        override_quiet="n" ;;
      h|?)
        _set_overrides
        _usage \
          0 ;;
      *)
        _msg=(
          "Invalid argument '${arg}'"
        )
        _msg_error \
          "${_msg[*]}" \
          0
        _usage \
          1 ;;
    esac
  done
}

_input_sound_check() {
  local \
    _msg=()
  if [[ ! -e "${input_sound}" ]]; then
    _msg=(
      "Input sound file"
      "'${input_sound}' does not exist."
    )
    echo \
      "${_msg[*]}" \
      1>&2
    exit \
      1
  else
    input_sound="$(
      realpath \
        "${input_sound}")"
  fi
}

# Set defaults and, if present, overrides
# from command line option parameters
_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "make" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "span" \
    "type" \
    "uniform"
  _set_override \
    "sound" \
    "encode" \
    "n"
}

# Shows configuration options.
_show_config() {
  _msg_info "audiopic2vid configuration"
  _msg_info "                Make date:   ${make_date}"
  _msg_info "                Span type:   ${span_type}"
  _msg_info "             Sound encode:   ${sound_encode}"
  _msg_info "              Output file:   ${output_video}"
  _msg_info "         Input sound file:   ${input_sound}"
  _msg_info "           Input pictures:"
  _show_config_input_pictures
}

_show_config_input_pictures() {
  local \
    _pic
  for _pic in "${input_pictures[@]}"; do
    _msg_info "                             ${_pic}"
  done
}

_globals
_global_variables

_cmdline_parse \
  "$@"
shift \
  $((
    OPTIND - 1 ))
output_video="${1}"
input_sound="${2}"
_input_sound_check
shift \
  2
input_pictures=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${span_type}"
  "${sound_encode}"
  "${output_video}"
  "${input_sound}"
  "${input_pictures[@]}"
)
_audiopic2vid \
  "${app_opts[@]}"
