#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" || \
source \
  "${_crash_bash}"

# shellcheck disable=SC2034
_global_variables() {
  in_file=""
  out_file=""
  clip_length=""
  color=""
  quiet=""
}

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    "medialength" \
    "media-tools"
  _check_cmd \
    "mediaclip" \
    "media-tools"
}

_clip_random() {
  local \
    _in_file="${1}" \
    _out_file="${2}" \
    _clip_length="${3}" \
    _clip_start_upper \
    _clip_start \
    _length \
    _mediaclip_opts=() \
    _msg=()
  if [[ "${quiet}" == "n" ]]; then
    _mediaclip_opts+=(
      -v
    )
  fi
  _length="$((
    "$(medialength \
      "${_in_file}")" / 1 ))"
  if [[ "${_length}" == "" ]]; then
    _msg=(
      "File '${_in_file}'"
      "seems corrupted."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  if (( "${_length}" < "${_clip_length}" )); then
    _msg=(
      "File '${_in_file}' has length '${_length}'"
      "shorter than input clip length '${_clip_length}'."
    )
  fi
  _clip_start_upper="$((
    "${_length}" - "${_clip_length}" ))"
  _clip_start="$(
    shuf \
      -i \
        "0-${_clip_start_upper}")"
  mediaclip \
    "${_mediaclip_opts[@]}" \
    "${_in_file}" \
    "${_clip_start}" \
    "${_clip_length}" \
    "${_out_file}"
}

# Set defaults
_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "clip" \
    "length" \
    "1"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Clip a video from a random point given a length

Usage:
  ${app_name}
    [options]
    <input-video>
    <output-video>
  options:
     -l                   Clip length.
                          Default: ${clip_length}
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'l:cvh?' \
    arg; do
  case \
    "${arg}" in
    l)
      override_clip_length="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides && \
      _usage \
        0 ;;
    *)
      msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${msg[*]}" \
        0
      _usage \
        1 ;;
  esac
done
shift \
  $(( OPTIND - 1 ))
if (( ${#} < 1 )); then
  _usage \
    1
fi
in_file="${1}"
out_file="${2}"
_set_overrides
_config_user_init \
  "media-tools"
_clip_random \
  "${in_file}" \
  "${out_file}" \
  "${clip_length}"
