#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_medialength() {
  local \
    _media="${1}" \
    _ffprobe_opts=()
  _ffprobe_opts=(
    -show_entries 
      'format=duration'
    -v
      'quiet'
    -of
     csv="p=0"
  )
  ffprobe \
    -i \
      "${_media}" \
    ${_ffprobe_opts[@]}
}

_media="${1}"

(( $# < 1 )) && \
  _usage=(
    "Usage:"
      "medialength"
        "<video_file>"
  ) && \
  echo \
    "${_usage[*]}" && \
    exit

_medialength \
  "${_media}" \

# vim: ft=sh syn=sh et
