#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>"/dev/null" || \
source \
  "${_crash_bash}"

# Check all required programs
# are available
_requirements() {
  true
}

# shellcheck disable=SC2034
_global_variables() {
  clip_date=""
  out_stdout=""
  in_file=""
  cut_start=""
  cut_length=""
  out_file=""
  color=""
  quiet=""
}

_ffmpeg_options_load() {
  local \
    ffmpeg_options
  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
  [ -e "${ffmpeg_options}" ] && \
    source \
      "${ffmpeg_options}" || \
  true
}

# Cut video from A to B
# $1: output video file
# $2: time to cut in (in seconds)
# $3: time to cut in (in seconds)
# $4: input video file
_mediaclip() {
  local \
    _in="${1}" \
    _start="${2}" \
    _length="${3}" \
    _out=(
      "${4}"
    ) \
    _opts=()
  _msg_info "out: ${_out[*]}"
  if [[ "${_out[*]}" == "" ]] || \
     [[ "${out_stdout}" == "y" ]]; then
    _out+=(
      -
    )
  fi
  _opts+=(
    "${_ffmpeg_opts[@]}"
    -ss 
      "${_start}"
    -i
      "${_in}"
    -to
      "${_length}"
    -reset_timestamps
      1
    -map 
      0
    -c 
      copy
  )
  ffmpeg \
    "${_opts[@]}" \
    "${_out[*]}"
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  _set_override \
    "clip" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "confirm" \
    "disabled" \
    "y"
  _set_override \
    "out" \
    "stdout" \
    "n"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                Clip date:   ${clip_date}"
  _msg_info "               Clip start:   ${cut_start}"
  _msg_info "              Clip length:   ${cut_length}"
  _msg_info "                 Out file:   ${out_file}"
  _msg_info "                  In file:   ${in_file}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Cut media files

Usage:
  ${app_name}
    [options]
    <in-file>
    <cut-start>
    <cut-length>
    <out-file>

  options:
     -s          Output to stdout.
     -h          This message.
     -v          Enable verbose output.

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'scvh?' \
    arg; do
  case \
    "${arg}" in
    s)
      override_out_stdout="y" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
    _set_overrides
    _usage \
      1 ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 ))

(( $# < 3 )) && \
  _usage \
    1
if (( $# < 3 )); then
  _msg=(
    "No output file given,"
    "will return to standard output."
  )
  _msg_info \
    "${_msg[*]}"
fi
in_file="${1}"
cut_start="${2}"
cut_length="${3}"
if (( "${#}" == 4 )); then
  out_file="${4}"
fi
_set_overrides
_config_user_init \
  "media-tools"
_ffmpeg_options_load
if [ ! -e "${in_file}" ]; then
  _msg=(
    "File '${in_file}' does not exist."
  )
  _msg_error \
   "${_msg[*]}" \
    1
fi
_show_config
_mediaclip \
  "${in_file}" \
  "${cut_start}" \
  "${cut_length}" \
  "${out_file}"
