#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    'ffmpeg'
}


# shellcheck disable=SC2034
_global_variables() {
  out_stdout=""
  in_file=""
  chunks_amount=""
  chunks_length=""
  out_prefix=""
  chunks_selected=()
  color=""
  quiet=""
}

_ffmpeg_options_load() {
  local \
    ffmpeg_options
  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
  [ -e "${ffmpeg_options}" ] && \
    source \
      "${ffmpeg_options}" || \
  true
}

# Cut video from A to B
# $1: output video file
# $2: time to cut in (in seconds)
# $3: time to cut in (in seconds)
# $4: input video file
_mediaclip() {
  local \
    _in="${1}" \
    _start="${2}" \
    _length="${3}" \
    _out=(
      "${4}"
    ) \
    _opts=()
  _msg_info "out: ${_out[*]}"
  if [[ "${_out[*]}" == "" ]] || \
     [[ "$(_get \
             "out" \
	     "stdout")" == "y" ]]; then
    _out+=(
      -
    )
  fi
  _opts+=(
    "${_ffmpeg_opts[@]}"
    -ss 
      "${_start}"
    -i
      "${_in}"
    -to
      "${_length}"
    -reset_timestamps
      1
    -map 
      0
    -c 
      copy
  )
  ffmpeg \
    "${_opts[@]}" \
    "${_out[*]}"
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  _set_override \
    "split" \
    "mode" \
    "uniform"
  _set_override \
    "chunks" \
    "amount" \
    "2"
  _set_override \
    "chunks" \
    "length" \
    "600"
 _set_override \
    "out" \
    "stdout" \
    "n"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}


# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Split media files

Usage:
  $(_get "app" "name")
    [options]
    <in_file>
    (<out_prefix>)
  modes:
     uniform              to split the media in a given amount
                          of uniformly sized chunks
     fixed                to split the media in chunks of
                          a given length
  options:
     -m                   Split mode;
                          Default: $(_get "split" "mode")
     -n                   Amount of uniform chunks in which
                          the media has to be split when
			  'uniform' split mode is selected.
                          Default: $(_get "chunks" "amount")
     -l                   Length of the chunks in seconds
                          in which the media has to be split
			  when 'fixed' split mode is selected.
                          Default: $(_get "chunks" "length")
     -r                   Returns only selected chunks.
     -s                   Output to stdout.
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:n:l:r:scvh?' \
    arg; do
  case \
    "${arg}" in
    m) override_split_mode="${OPTARG}" ;;
    n) override_chunks_amount="${OPTARG}" ;;
    l) override_chunks_length="${OPTARG}" ;;
    r) chunks_selected+=(
	"${OPTARG}"
       ) ;;
    s) override_out_stdout="y" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
	 _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0 && \
    _set_overrides && \
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))

(( $# < 1 )) && \
  _usage \
    1
(( $# < 2 )) && \
  _msg_info \
    "no prefix given for output files, same as the input filename will be used"
in_file="${1}"
(( $# == 2 )) && \
  out_prefix="${2}"
_set_overrides
_config_user_init \
  "media-tools"
_ffmpeg_options_load
_mediasplit \
  "${in_file}" \
  "${split_mode}" \
  "${chunks_amount}" \
  "${chunks_length}" \
  "${out_prefix}" \
  "${chunks_selected[@]}"
