#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>"/dev/null" || \
source \
  "${_crash_bash}"

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    'bc'
  _check_cmd \
    'mediaclip'
}

# shellcheck disable=SC2034
_global_variables() {
  out_stdout=""
  in_file=""
  split_mode=""
  chunks_amount=""
  chunks_length=""
  out_prefix=""
  chunks_selected=()
  split_date=""
  color=""
  quiet=""
}

_ffmpeg_options_load() {
  local \
    ffmpeg_options
  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
  [ -e "${ffmpeg_options}" ] && \
    source \
      "${ffmpeg_options}" || \
  true
}

_uniform_split() {
  _length="$( \
    echo \
      "${_duration} / ${_amount}" | \
      bc)"
}

_fixed_split() {
  _amount="$( \
    echo \
      "${_duration} / ${_length};" \
      "scale 0" | \
      bc)"
}

# Cut video by chunks amount
# or length
# $1: input media file
# $2: filename prefix for media file
# $3: split mode ('uniform' or 'fixed')
# $4: chunks amount if 'uniform' mode is selected
# $5: chunks length if 'fixed' mode is selected
# $@: only render these chunks
_mediasplit() {
  local \
    _in="${1}" \
    _mode="${2}" \
    _prefix="${3}" \
    _amount="${4}" \
    _length="${5}" \
    _chunk \
    _chunks=() \
    _duration \
    _start \
    _out \
    _ext
  shift \
    5
  _chunks=(
    "$@"
  )
  _ext="$( \
    _get_ext \
      "${_in}")"
  _duration="$( \
    medialength \
      "${_in}")"
  "_${_mode}_split"
  if [[ "${_chunks[*]}" == "" ]]; then
    _chunks+=(
      $(seq \
          "${_amount}")
    )
  fi
  for _chunk \
    in $(seq \
           "${_amount}"); do
    if [[ " ${_chunks[*]} " == *" ${_chunk} "* ]]; then
      _msg_info \
        "rendering chunk ${_chunk}"
      _start="$( \
        echo \
	  "(${_chunk} - 1) * ${_length}" | \
	  bc)"
      _out="${_prefix}.${_chunk}.${_ext}"
      mediaclip \
        "${_in}" \
	"${_start}" \
	"${_length}" \
	"${_out}"
    fi
  done
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "split" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "out" \
    "prefix" \
    "$(_rm_ext \
         "$(_get \
	      "in" \
	      "file")")"
  _set_override \
    "split" \
    "mode" \
    "uniform"
  _set_override \
    "chunks" \
    "amount" \
    "2"
  _set_override \
    "chunks" \
    "length" \
    "600"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "               Split date:   ${split_date}"
  _msg_info "               Split mode:   ${split_mode}"
  _msg_info "                  In file:   ${in_file}"
  _msg_info "            Output prefix:   ${out_prefix}"
  _msg_info "            Chunks amount:   ${chunks_amount}"
  _msg_info "            Chunks length:   ${(chunks_length}"
  _msg_info "          Selected chunks:   ${chunks_selected[*]}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Split media files

Usage:
  ${app_name}
    [options]
    <in_file>
    (<out_prefix>)

  modes:
     uniform              to split the media in a given amount
                          of uniformly sized chunks
     fixed                to split the media in chunks of
                          a given length

  options:
     -y                   Do not ask if to overwrite
                          output.
                          Default: "${quiet}"
     -m                   Split mode;
                          Default: ${split_mode}
     -n                   Amount of uniform chunks in which
                          the media has to be split when
                          'uniform' split mode is selected.
                          Default: ${chunks_amount}
     -l                   Length of the chunks in seconds
                          in which the media has to be split
                          when 'fixed' split mode is selected.
                          Default: ${chunks_length}
     -r                   Returns only selected chunks.
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'ym:n:l:r:scvh?' \
    arg; do
  case \
    "${arg}" in
    y) override_confirm_disabled="y" ;;
    m) override_split_mode="${OPTARG}" ;;
    n) override_chunks_amount="${OPTARG}" ;;
    l) override_chunks_length="${OPTARG}" ;;
    r) chunks_selected+=(
	"${OPTARG}"
       ) ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'"
      )
    _msg_error \
      "${_msg[*]}" \
      0
    _set_overrides
    _usage \
      1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 ))

if (( "${#}" < 1 )); then
  _usage \
    1
fi
if (( "${#}" < 2 )); then
  _msg=(
    "No prefix given for output"
    "files, same as the input"
    "filename will be used."
  )
  _msg_info \
    "${_msg[*]}"
fi
in_file="${1}"
(( $# == 2 )) && \
  out_prefix="${2}"
_set_overrides
_config_user_init \
  "media-tools"
_ffmpeg_options_load
_show_config
_mediasplit \
  "${in_file}" \
  "${split_mode}" \
  "${out_prefix}" \
  "${chunks_amount}" \
  "${chunks_length}" \
  "${chunks_selected[@]}"
