#!/usr/bin/env bash

# Merges an audio track and a video file
_mkaudiovid() {
  local \
    _aud="${1}" \
    _vid="${2}" \
    _out="${3}" \
    _opts=()

  _opts=(
    -i "${_vid}"
    -i "${_aud}"
    -c copy
    -map 0:v:0
    -map 1:a:0
    # -f 'mp4'
    )
  ffmpeg \
    "${_opts[@]}" \
    "${_out}"
}

_aud="${1}"
_vid="${2}"
_out="${3}"

_mkaudiovid "${_aud}" "${_vid}" "${_out}"
