#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" || \
source \
  "${_crash_bash}"

_global_variables() {
  make_date=""
  out_gif=""
  in_media=()
  target_length=""
  target_program=""
  color=""
  quiet=""
}



_mkgif_ffmpeg() {
  _input_mp4="alt-tab.mp4"; \
  _output_gif="alt-tab.gif"; \
  _fps=5; \
  _scale_width="216"; \
  _scale_flags="lanczos"; \
  _palettegen_max_colors="32"; \
  _paletteuse_dither="bayer"; \
  
  _filter_complex_cmds=(
    "fps=${_fps}"
    "scale=${_scale_width}:480:flags=${_scale_flags}"
    "split[s0][s1]"
  )
  _filter_complex_cmds_string="$(
    IFS=","; \
    echo \
      "${_filter_complex_cmds[*]}")"
  
  _filter_complex=(
    "${_filter_complex_cmds_string}"
    "[s0]palettegen=max_colors=${_palettegen_max_colors}[p]"
    "[s1][p]paletteuse=dither=${_paletteuse_dither}"
  )
  
  _filter_complex_string="$(
    IFS=";"; \
    echo \
      "${_filter_complex[*]}")"
  
  _ffmpeg_opts=(
    -y
    -i
      "${_input_mp4}"
    -filter_complex
      "${_filter_complex_string}"
  )
  echo "${_ffmpeg_opts[*]}"
  ffmpeg \
    "${_ffmpeg_opts[@]}" \
    "${_output_gif}"
}

# Merges together pictures to make a gif
_mkgif() {
  local \
    _out="${1}" \
    _len="${2}" \
    _pics=()
  shift 2
  _pics=("${@}")
  convert \
    -delay "${_len}" \
    -loop 0 \
    "${_pics[@]}" \
    "${_out}"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                Make date:   ${make_date}"
  _msg_info "              Input media:   ${in_media[*]}"
  _msg_info "               Output GIF:   ${out_gif}"
  _msg_info "            Target length:   ${target_length}"
  _msg_info "           Output program:   ${target_program}"
}

_usage() {
  local \
    _exit_code="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Merges pictures or convert videos into animated GIFs.

Usage:
  ${app_name}
    [options]
    <out-gif>
    [in-file]

  options:

     -i                   Explicitly set input type
                          for conversion.
                          It can be 'picture' or
                          'video'.
                          Default: ${input_type}

     -l <length>          Output GIF target length
                          (when creating animated GIFs
                          from pictures.)
                          Default: ${_target_length}

     -p <program>         Explicitly set program
                          to use. It can be
                          'ffmpeg' or 'imagemagick'.
                          Default: ${target_program}

     -h                   This message.
     -v                   Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit_code}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'i:p:l:cvh?' \
    arg; do
  case \
    "${arg}" in
    i)
      override_input_type="${OPTARG}" ;;
    p)
      override_target_program="${OPTARG}" ;;
    l)
      override_target_length="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _set_overrides
  _msg=(
    "Output gif argument"
    "is required."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _usage \
    1
fi
out_gif="${1}"
if (( "$#" < 2 )); then
  _msg=(
    "Input file(s) argument(s)"
    "is (are) required."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _usage \
    1
fi
in_media=(
  "$@"
)
_set_overrides
_config_user_init \
  "media-tools"
_ffmpeg_options_load
_show_config
app_opts=(
  "${out_video}"
  "${in_video}"
  "${in_duration}"
  "${out_duration}"
)

_out="${1}"
_len="${2}"
shift 2
_pics="${@}"

_mkgif \
  "${_out}" \
  "${_len}" \
  "${_pics[@]}"
