#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Merges together pictures to maje a gif
_mkgif() {
  local \
    _out="${1}" \
    _len="${2}" \
    _pics=()
  shift 2
  _pics=("${@}")

  convert \
    -delay "${_len}" \
    -loop 0 \
    "${_pics[@]}" \
    "${_out}"
}

_out="${1}"
_len="${2}"
shift 2
_pics="${@}"

_mkgif "${_out}" "${_len}" "${_pics[@]}"
