#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" || \
source \
  "${_crash_bash}"

_global_variables() {
  make_date=""
  out_gif=""
  in_media=()
  target_length=""
  target_program=""
  color=""
  quiet=""
}

_mkgif_ffmpeg() {
  local \
    _output_gif="${1}" \
    _input_mp4="${2}" \
    _filter_complex=() \
    _filter_complex_string \
    _filter_complex_cmds=() \
    _filter_complex_cmds_string \
    _fps \
    _scale_width \
    _scale_flags \
    _palettegen_max_colors \
    _paletteuse_dither
  _fps=5
  if (( 2 < $# )); then
    _fps="${3}"
  fi
  _scale_width="216"
  if (( 3 < $# )); then
    _scale_width="${4}"
  fi
  _scale_flags="lanczos"
  if (( 4 < $# )); then
    _scale_flags="${5}"
  fi
  _palettegen_max_colors="32"
  if (( 5 < $# )); then
    _palettegen_max_colors="${6}"
  fi
  _paletteuse_dither="bayer"
  if (( 6 < $# )); then
    _palettegen_dither="${7}"
  fi
  _filter_complex_cmds=(
    "fps=${_fps}"
    "scale=${_scale_width}:480:flags=${_scale_flags}"
    "split[s0][s1]"
  )
  _filter_complex_cmds_string="$(
    IFS=","; \
    echo \
      "${_filter_complex_cmds[*]}")"
  _filter_complex=(
    "${_filter_complex_cmds_string}"
    "[s0]palettegen=max_colors=${_palettegen_max_colors}[p]"
    "[s1][p]paletteuse=dither=${_paletteuse_dither}"
  )
  
  _filter_complex_string="$(
    IFS=";"; \
    echo \
      "${_filter_complex[*]}")"
  
  _ffmpeg_opts=(
    -y
    -i
      "${_input_mp4}"
    -filter_complex
      "${_filter_complex_string}"
  )
  _msg=(
    "Running ffmpeg with options"
    "'${_ffmpeg_opts[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  ffmpeg \
    "${_ffmpeg_opts[@]}" \
    "${_output_gif}"
}

# Merges together pictures to make a gif
_mkgif_imagemagick() {
  local \
    _out="${1}" \
    _len="${2}" \
    _pics=() \
    _convert_opts=()
  shift \
    2
  _pics+=(
    "$@"
  )
  _convert_opts+=(
    -delay
      "${_len}"
    -loop
      0
  )
  convert \
    "${_convert_opts[@]}" \
    "${_pics[@]}" \
    "${_out}"
}

_mkgif() {
  local \
    _out_gif="${1}" \
    _target_length="${2}" \
    _target_program="${3}" \
    _in_media=() \
    _cmd \
    _args=()
  shift \
    3
  _in_media+=(
    "$@"
  )
  if [[ "${_target_program}" == "imagemagick" ]]; then
    _args+=(
      "${_out_gif}"
      "${_target_length}"
      "${_in_media[@]}"
    )
  elif [[ "${_target_program}" == "ffmpeg" ]]; then
    _args+=(
      "${_out_gif}"
      # "${_target_length}"
      "${_in_media[@]}"
    )
  fi
  _cmd="_mkgif_${_target_program}"
  "${_cmd}" \
    "${_args[@]}"
}

_in_media_check() {
  local \
    _file
  for _file in "${in_media[@]}"; do
    if [[ ! -e "${_file}" ]]; then
      _msg=(
        "File '${_file}'"
	"does not exist."
      )
      _msg_error \
        "${_msg[*]}" \
	1
    fi
  done
}

_out_gif_auto_detect() {
  local \
    _in_media_files_amount \
    _in_file_name \
    _out_gif
  _in_media_files_amount="${#in_media[@]}"
  if (( "${_in_media_files_amount}" < 1 )); then
    _out_gif="<input-file-name>.gif"
  else
    _in_file_name="$(
      basename \
        "${in_media[0]}")"
    _out_gif="${_in_file_name%.*}"
  fi
  _set_override \
    "out" \
    "gif" \
    "${_out_gif}"
}

_target_program_auto_detect() {
  local \
    _in_media_files_amount \
    _input_file \
    _target_program
  _target_program="ffmpeg"
  _in_media_files_amount="${#in_media[@]}"
  if (( 0 < "${_in_media_files_amount}" )); then
    _input_file="${in_media[0]}"
    if [[ "${_input_file}" == *".jpg" || \
          "${_input}" ]]; then
      _target_program="imagemagick"
    elif [[ "${_input_file}" == *".mp4" ]]; then
      _target_program="ffmpeg"
    else
      _ext="${_input_file##*.}"
      _msg=(
        "I'm not in the mood to"
        "go to pick the mime/type"
        "parser right now to get if"
        "an '${_ext}' is a picture"
        "or a video, you tell me."
      )
      _msg_info \
        "${_msg[*]}"
    fi
  fi
  _set_override \
    "target" \
    "program" \
    "${_target_program}"
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "make" \
    "date" \
    "$(_get_date_human)"
  _in_media_check
  _out_gif_auto_detect
  _set_override \
    "out" \
    "gif" \
    "${in_media[@]}.gif"
  _set_override \
    "in" \
    "duration" \
    "3"
  _set_override \
    "out" \
    "duration" \
    "${in_duration}"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                Make date:   ${make_date}"
  _msg_info "              Input media:   ${in_media[*]}"
  _msg_info "               Output GIF:   ${out_gif}"
  _msg_info "            Target length:   ${target_length}"
  _msg_info "           Output program:   ${target_program}"
}

_usage() {
  local \
    _exit_code="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Merges pictures or convert videos into animated GIFs.

Usage:
  ${app_name}
    [options]
    <out-gif>
    [in-file]

  options:

     -i                   Explicitly set input type
                          for conversion.
                          It can be 'picture' or
                          'video'.
                          Default: ${input_type}

     -l <length>          Output GIF target length
                          (when creating animated GIFs
                          from pictures.)
                          Default: ${_target_length}

     -p <program>         Explicitly set program
                          to use. It can be
                          'ffmpeg' or 'imagemagick'.
                          Default: ${target_program}

     -h                   This message.
     -v                   Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit_code}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'i:p:l:cvh?' \
    arg; do
  case \
    "${arg}" in
    i)
      override_input_type="${OPTARG}" ;;
    p)
      override_target_program="${OPTARG}" ;;
    l)
      override_target_length="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _set_overrides
  _msg=(
    "Output gif argument"
    "is required."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _usage \
    1
fi
out_gif="${1}"
if (( "$#" < 2 )); then
  _msg=(
    "Input file(s) argument(s)"
    "is (are) required."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _usage \
    1
fi
in_media=(
  "$@"
)
_set_overrides
_config_user_init \
  "media-tools"
_ffmpeg_options_load
_show_config
app_opts=(
  "${out_gif}"
  "${target_length}"
  "${target_program}"
  "${in_media[@]}"
)
_mkgif \
  "${app_opts[@]}"
