#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    "ffmpeg"
}

# shellcheck disable=SC2034
_global_variables() {
  out_video=""
  in_audio=""
  in_video=""
  video_encode=""
  audio_mode=""
  out_stdout=""
  color=""
  quiet=""
}

_ffmpeg_options_load() {
  local \
    ffmpeg_options
  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
  [ -e "${ffmpeg_options}" ] && \
    source \
      "${ffmpeg_options}" || \
  true
}

# Merges sound with a sequence of vids
# $1: output file
# $2: sound file
# $@: videos
_audiovid2vid() {
  local \
    _mode="${1}" \
    _out="${2}" \
    _aud="${3}" \
    _vid="${4}" \
    _opts=() \
    _overlap \
    _vidaud \
    _mute \
    _ext
  if [[ "${quiet}" == "y" ]]; then
    _ffmpeg_opts+=(
      -y
    )
  fi
  _opts+=(
    "${_ffmpeg_opts[@]}"
    #  -loop 1
  )
  if [[ "${_mode}" == 'replace' ]]; then
    _opts+=(
      -i "${_aud}"
      -i "${_vid}"
    )
  elif [[ "${_mode}" == "overlap" ]]; then
    _ext="${_vids##*.}"
    _vidaud="$( \
      mktemp).opus"
    _overlap="$( \
      mktemp).opus"
    _mute="$( \
      mktemp).${_ext}"
    ffmpeg \
      -i \
        "${_vid}" \
      "${_vidaud}"
    audioverlap \
      "${_overlap}" \
      "${_aud}" \
      "${_vidaud}"
     vidmute \
       "${_vid}" \
       "${_mute}"
     _opts+=(
       -i "${_overlap}"
       -i "${_mute}"
     )
  fi
  if [[ "$(_get \
	  "video" \
	  "encode")" == "y" ]]; then
    _x265="true"
    _opts+=(
      -c:v
        libx265
      -pix_fmt
        yuv420p
  )
  elif [[ "$(_get \
               "video" \
	       "encode")" == "n" ]]; then
    _opts+=(
      -c:v
        copy
    )
  fi
  _opts+=(
    -c:a
      aac
    -b:a
      48k
    -shortest
  )
  ffmpeg \
    "${_opts[@]}" \
    "${_out}"
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  _set_override \
    "audio" \
    "mode" \
    "replace"
  _set_override \
    "video" \
    "encode" \
    "n"
  _set_override \
    "out" \
    "stdout" \
    "n"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                Make date:   $(_get "make" "date")"
  _msg_info "               Audio mode:   $(_get "audio" "mode")"
  _msg_info "                   Encode:   $(_get "video" "encode")"
  _msg_info "             Output video:   $(_get "out" "video")"
  _msg_info "              Input audio:   $(_get "in" "audio")"
  _msg_info "              Input video:   $(_get "in" "video")"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Cut media files

Usage:
  $(_get "app" "name")
    [options]
    <out_video>
    <in_audio>
    <in_video>
  options:
     -m                   Audio mode (replace, overlap)
                          Default: $(_get "audio" "mode")
     -e                   Whether to encode the resulting video
                          or use encoder from input media.
			  Default: $(_get "video" "encode")
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:ecvh?' \
    arg; do
  case \
    "${arg}" in
    m) override_audio_mode="${OPTARG}" ;;
    e) override_video_encode="y" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
	 _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0 && \
    _set_overrides && \
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))

(( $# < 3 )) && \
  _set_overrides && \
  _usage \
    1
_set \
  "out" \
  "video" \
  "${1}"
_set \
  "in" \
  "audio" \
  "${2}"
in_video="${3}"
_set_overrides
_config_user_init \
  "media-tools"
_ffmpeg_options_load
_show_config
app_opts=(
  "$(_get \
       "audio" \
       "mode")"
  "$(_get \
       "out" \
       "video")"
  "$(_get \
       "in" \
       "audio")"
  "${in_videos[@]}"
)
_audiovid2vid \
  "${app_opts[@]}"
