#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="$( \
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"

# Resize maintaining original proportions
# and adding colored pad
_mkpad () {
  local \
    _in="${1}" \
    _out="${2}" \
    _w="${3}" \
    _h="${4}" \
    _color="${5}" \
    _pad_opts=() \
    _scale_opts=() \
    _opts=() \
    _vf

  _pad_opts=(
    "${_w}"
    "${_h}"
    "-1"
    "-1"
    "color=${_color}")

  _scale_opts=(
    "${_w}"
    "${_h}"
    "force_original_aspect_ratio=decrease")
  
  _vf="$(IFS=":"; \
         echo \
	   "${_scale_opts[*]},${_pad_opts[@]}")"

  _opts=(
    -i "${_in}"
    -vf "${_vf}"
    -c:v libx264
    -preset slow
    -crf 18)

  ffmpeg \
    "${_opts[@]}" \
    "${_out}"
}

if (( $# < 5 )); then
  _msg=(
    "Usage:"
    "  ${app_name}"
    "    <in>"
    "    <out>"
    "    <width>"
    "    <height>"
    "    <color>"
  )
  _msg_info \
    "${_msg[*]}"
fi

_in="${1}"
_out="${2}"
_w="${3}"
_h="${4}"
_color="${5}"

app_opts=(
  "${_in}"
  "${_out}"
  "${_w}"
  "${_h}"
  "${_color}"
)
_mkpad \
  "${app_opts[@]}"
