#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Stitches pics together
_picstitch() {
  local \
    _out="${1}"
  shift
  local \
    _pics=("${@}") \
    _tmp
  _tmp="$(mktemp -d)"
  pto_gen \
    "${_pics[@]}" \
    -o "${_tmp}/picstitch.pto"
  hugin_executor \
    --stitching \
    --prefix="${_tmp}/picstitch" \
    "${_tmp}/picstitch.pto"
  convert \
    "${_tmp}/picstitch.tif" \
    "${_out}"
}

_out="${1}"
shift
_pics=("${@}")

_picstitch "${_out}" "${_pics[@]}"
