#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_single_ping() {
  local \
    _in="${1}" \
    _component="${2}"
  identify \
    -ping \
    -format "%${_component}" \
    "${_in}"
}

_get_height() {
  local \
    _in="${1}"
  _single_ping "${_in}" "h"
}

_get_width() {
  local \
    _in="${1}"
  _single_ping "${_in}" "w"
}

_picscale() {
  local \
    _in="${1}" \
    _out="${2}" \
    _scale="${3}" \
    _w \
    _h \
    _wnew \
    _hnew
  _h="$(_get_height "${_in}")"
  _w="$(_get_width "${_in}")"
  _wnew="$(( (_w * _scale) / 100))"
  _hnew="$(( (_h * _scale) / 100))"
  convert \
    "${_in}" \
    -resize "${_wnew}x${_hnew}"\! \
    "${_out}"
}

_in="${1}"
_out="${2}"
_scale="${3}"

_picscale "${_in}" "${_out}" "${_scale}"
