#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  in_files=()
  out_file=""
  encode_mode=""
  color=""
  quiet=""
}

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    "ffmpeg"
}

_ffmpeg_options_load() {
  local \
    ffmpeg_options
  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
  [ -e "${ffmpeg_options}" ] && \
    source \
      "${ffmpeg_options}" || \
  true
}

# Con(cat)enate video files
# $1: output video file
# $@: input video files (sorted)
_vidcat() {
  local \
    _out="${1}" \
    _i=1 \
    _in=() \
    _opts=() \
    _vf="" \
    _vids
  shift \
    1
  _in=(
    "$@"
  )
  _vids="$( \
    mktemp)"
  for _vid \
    in "${_in[@]}"; do
    _vid="$( \
      realpath \
        "${_vid}")"
    echo \
      "file '${_vid}'" >> \
      "${_vids}"
   _vf="${_vf} [${_i}:v] [${_i}:a]"
   _i=$((_i + 1))
  done
  _vf="${_vf} concat=n=${_i}:v=1:a=1 [v] [a]"
  cat \
    "${_vids}"
  _opts=(
    -safe
      0
    -i
      ${_vids}
    -filter_complex
      "${_vf}"
    -map
      "[v]"
    -map
      "[a]"
    -f
      mp4
    -vcodec
      libx265
  )
  ffmpeg \
    "${_opts[@]}" \
    "${_out}"
  # echo \
  #   "${_mm}"
  [[ ! $? -eq 0 ]] && \
    _concat
}

_concat() {
  local \
    _opts=()
  _opts=(
    -y
    -f
      concat
    -safe
      0
    -i
      "${_vids}"
    -c
      copy
  )
  ffmpeg \
    "${_opts[@]}" \
    "${_out}"
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  _set_override \
    "encode" \
    "mode" \
    "quality"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Concatenate video files

Usage:
  $(_get "app" "name")
    [options]
    <output_file>
    [input_file]
  options:
     -m                   Video encode mode ('quolity', 'size').
                          Default: $(_get "encode" "mode")
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:cvh?' \
    arg; do
  case \
    "${arg}" in
    m) override_encode_mode="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
(( ${#} < 2 )) && \
  _usage \
    1
out_file="${1}"
shift \
  1
in_files=(
  "$@"
)
_vidcat \
  "${out_file}" \
  "${in_files[@]}"
