#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>"/dev/null" || \
source \
  "${_crash_bash}"

# shellcheck disable=SC2034
_global_variables() {
  in_file=""
  out_file=""
  scale_factor=""
  encode_mode=""
  gpu_type=""
  color=""
  quiet=""
}

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    "ffmpeg"
}

_ffmpeg_options_load() {
  local \
    ffmpeg_options
  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
  [ -e "${ffmpeg_options}" ] && \
    source \
      "${ffmpeg_options}" || \
  true
}

_encode_one() {
  _run_opts=(
    -i
      "${_in}"
    "${_opts[@]}"
  )
  _msg=(
    "Running ffmpeg with arguments"
    "'${_run_opts[@]} ${_out}'."
  )
  _msg_info \
    "${_msg[*]}"
  ffmpeg \
    "${_run_opts[@]}" \
    "${_out}"
}

_encode_many() {
  local \
    _chunk \
    _chunk_compressed \
    _chunks=() \
    _chunks_amount \
    _file_name \
    _mediasplit_opts=() \
    _videocat_opts=()
  if [[ "${quiet}" == "n" ]]; then
    _mediasplit_opts+=(
      -v
    )
    _videocat_opts+=(
      -v
    ) 
  fi
  _file_name="${_in%.mp4}"
  _chunks_amount="$((
    "${_length}" / "${_length_max}"))"
  _mediasplit_opts+=(
    -l
      "${_length_max}"
  )
  mediasplit \
    "${_mediasplit_opts[@]}" \
    "${_in}"
  _chunks=()
  for _index \
    in $(seq \
           "${_chunks_amount}"); do
    _chunk="${_file_name}.${_index}.mp4"
    _chunk_compressed="${_file_name}.compressed.${_index}.mp4"
    _chunks+=(
      "${_chunk_compressed}"
    )
    _run_opts=(
      -i
        "${_chunk}"
      "${_opts[@]}"
    )
    _msg=(
      "Running ffmpeg with arguments"
      "'${_run_opts[@]} ${_chunk_compressed}'."
    )
    _msg_info \
      "${_msg[*]}"
    ffmpeg \
      "${_run_opts[@]}" \
      "${_chunk_compressed}"
  done
  vidcat \
    "${_vidcat_opts[@]}" \
    "${_out}" \
    "${_chunks[@]}"
  rm \
    -rf \
  "${_chunks[@]}"
}

_vidscale() {
  local \
    _in="${1}" \
    _out="${2}" \
    _scale="${3}" \
    _mode="${4}" \
    _gpu_type="${5}" \
    _scale_opts=() \
    _opts=() \
    _vcodec \
    _crf \
    _run_opts=() \
    _length \
    _length_max \
    _preset \
    _msg=()
  _preset="fast"
  _vcodec="libx264"
  if [[ "${_mode}" == 'quality' ]]; then
    _crf=18
  elif [[ "${_mode}" == 'size' ]]; then
    _crf=30
    _preset="slow"
  elif [[ "${_mode}" == 'speed' ]]; then
    _crf="25"
    _preset="ultrafast"
    _length_max="$((
      60 * 30 ))"
  elif [[ "${_mode}" == 'gpu' ]]; then
    if [[ "${_type}" == "" ]]; then
      _msg=(
        "To use 'gpu' encode"
	"mode you need a discrete"
	"video card."
      )
      _msg_error \
        "${_msg[*]}"
    fi
    if [[ "${_type}" == "nvidia" ]]; then
      _vcodec="h264_nvenc"
      _opts+=(
        -hwaccel
          "cuvid"
        -hwaccell_output_format
          "cuda"
        -c:v
          "h264_cuvid"
      )
    fi
    _crf="25"
    _preset="slow"
    _length_max="$((
      60 * 30 ))"
  else
    _msg=(
      "Unknown encoding mode '${_mode}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  source \
    "${HOME}/.config/media-tools/ffmpeg_options"
  _scale_opts=(
    "scale=iw*${_scale}"
    "ih*${_scale}"
    "flags=neighbor"
  )
  _opts+=(
    "${ffmpeg_opts[@]}"
    -vf
      "$(IFS=":"; \
         echo \
           "${_scale_opts[*]}")"
    -c:v
      "${_vcodec}"
    -preset
      "${_preset}"
  )
  if [[ "${_mode}" != 'auto' ]]; then
    _opts+=(
      -crf
        "${_crf}"
    )
  fi
  if [[ "${_mode}" == "speed" ]]; then
    _length="$(
      medialength \
        "${_in}")"
    _length="${_length%.*}"
    if (( "${_length_max}" < "${_length}" )); then
      _encode_many
    else
      _encode_one
    fi
  else
    _encode_one
  fi
}

_gpu_type_auto_detect() {
  local \
    _amd \
    _intel \
    _nvidia \
    _type \
    _vgas
  _type=""
  _vgas="$(
    lspci |
      grep \
        "VGA")"
  _amd="$(
    echo \
      "${_vgas}" |
    grep \
      "AMD")"
  _nvidia="$(
    echo \
      "${_vgas}" |
    grep \
      "NVidia")"
  _intel="$(
    echo \
      "${_vgas}" |
    grep \
      "Intel")"
  if [[ "${_amd}" != "" ]]; then 
    _type="amd"
  elif [[ "${_nvidia}" != "" ]]; then 
    _type="nvidia"
  elif [[ "${_amd}" != "" ]]; then 
    _type="intel"
  fi
  _set_override \
    "gpu" \
    "type" \
	    "${_type}"
}

# Set defaults
_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _gpu_type_auto_detect
  _set_override \
    "encode" \
    "mode" \
    "quality"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Scale up or down a video by a factor

Usage:

  ${app_name}
    [options]
    <input_video>
    <output_video>
    <scale>

  options:
     -m                   Encode mode (quality, size,
                          speed, gpu, auto).
                          Default: ${encode_mode}
     -g                   GPU type for 'gpu' encode
			  mode ('amd', 'intel',
                          'nvidia')
                          Default: ${gpu_type}
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:g:cvh?' \
    arg; do
  case \
    "${arg}" in
    m)
      override_encode_mode="${OPTARG}" ;;
    g)
      override_gpu_type="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides && \
      _usage \
        0 ;;
    *)
      msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${msg[*]}" \
        0
      _usage \
        1 ;;
  esac
done
shift \
  $(( OPTIND - 1 ))
if (( ${#} < 3 )); then
  _usage \
    1
fi
in_file="${1}"
out_file="${2}"
scale_factor="${3}"
_set_overrides
_x265="true"
_ffmpeg_options_load
_config_user_init \
  "media-tools"
app_opts=(
  "${in_file}"
  "${out_file}"
  "${scale_factor}"
  "${encode_mode}"
  "${gpu_type}"
)
_vidscale \
  "${app_opts[@]}"
