#!/usr/bin/env bash

_ytencode() {
  local \
    _in="${1}" \
    _out="${2}" \
    _ffmpeg_opts=()
  _ffmpeg_opts=(
    -vf
     "yadif,format=yuv420p"
   -force_key_frames
     "expr:gte(t,n_forced/2)"
   -c:v
     "libx264"
   -crf
     18
   -bf 2
   -c:a
     "aac"
   -q:a
     1
   -ac
     2
   -ar
     48000
   -use_editlist
     0
   -movflags
     +faststart
  )
  ffmpeg \
    -i \
      "${_in}" \
    ${_ffmpeg_opts[@]} \
    "${_out}"
}

_in="${1}"
_out="${2}"

(( $# < 2 )) && \
  _usage=(
    "Usage:"
      "ytencode"
        "<input_file>"
	"<output_file>"
  ) && \
  echo \
    "${_usage[*]}" && \
    exit

_ytencode \
  "${_in}" \
  "${_out}"

