#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  in_file=""
  out_file=""
  encode_mode=""
  color=""
  quiet=""
}

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    "ffmpeg"
}

_ffmpeg_options_load() {
  local \
    ffmpeg_options
  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
  [ -e "${ffmpeg_options}" ] && \
    source \
      "${ffmpeg_options}" || \
  true
}

_ytencode() {
  local \
    _in="${1}" \
    _out="${2}" \
    _encode_mode="${3}" \
    _opts=() \
    _crf=0
  [[ "${_encode_mode}" == "quality" ]] && \
    _crf=18
  [[ "${_encode_mode}" == "size" ]] && \
    _crf=30
  _opts+=(
    "${_ffmpeg_opts[@]}"
    -vf
     "yadif,format=yuv420p"
   -force_key_frames
     "expr:gte(t,n_forced/2)"
   -c:v
     "libx265"
   -crf
     "${_crf}"
   -bf 2
   -c:a
     "aac"
   -q:a
     1
   -ac
     2
   -ar
     48000
   -use_editlist
     0
   -movflags
     +faststart
  )
  [[ "${_encode_mode}" == "fake" ]] && \
    _opts=(
      "${_ffmpeg_opts[@]}")
  ffmpeg \
    -i \
      "${_in}" \
    "${_opts[@]}" \
    "${_out}"
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  _set_override \
    "encode" \
    "mode" \
    "quality"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Convert media file for YouTube consumption

Usage:
  $(_get "app" "name")
    [options]
    <input_file>
    <output_file>
  options:
     -m                   Video encode mode ('quolity', 'size').
                          Default: $(_get "encode" "mode")
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:cvh?' \
    arg; do
  case \
    "${arg}" in
    m) override_encode_mode="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
(( ${#} < 1 )) && \
  _usage \
    1
_set \
  "in" \
  "file" \
  "${1}"
(( $# < 2 )) && \
  _out="$( \
    basename \
      "$( \
        _get \
          "in" \
          "file")")" && \
  _set \
    "out" \
    "file" \
    "$( \
      pwd)/${_out%.*}.yt.${_out#*.}"
[[ "$(_get \
	"out" \
	"file")" == "" ]] && \
  _set \
    "out" \
    "file" \
    "${2}"
_set_overrides
_config_user_init \
  "media-tools"
_ytencode \
  "$( \
    _get \
      "in" \
      "file")" \
  "$( \
    _get \
      "out" \
      "file")" \
  "$( \
    _get \
      "encode" \
      "mode")"
