#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

# Stitches pics together
_audiopic2vid() {
  local \
    _out="${1}"
    _aud="${2}"
  shift 2
  local \
    _pics=("${@}") \
    _tmp
  _tmp="$(mktemp -d)"

  ffmpeg \
    -loop 1 \
    -i "${_pics[@]}" \
    -i "${_aud}" \
    -c:v libx264 \
    -tune stillimage \
    -c:a aac \
    -b:a 48k \
    -pix_fmt yuv420p \
    -shortest "${_out}"
}

_out="${1}"
_aud="${2}"
shift 2
_pics=("${@}")

_audiopic2vid "${_out}" "${_aud}" "${_pics[@]}"
