#!/usr/bin/env bash

_in="${1}"
_out="${2}"

ffmpeg \
  -i "${_in}" \
  -vf yadif,format=yuv420p \
  -force_key_frames "expr:gte(t,n_forced/2)" \
  -c:v libx264 \
  -crf 18 \
  -bf 2 \
  -c:a aac \
  -q:a 1 \
  -ac 2 \
  -ar 48000 \
  -use_editlist 0 \
  -movflags +faststart \
  "${_out}"
